# Generated by Django 4.1.7 on 2023-03-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.CharField(max_length=64)),
                ('category', models.CharField(max_length=64)),
                ('picture', models.ImageField(upload_to='menu/')),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('s_price', models.FloatField()),
                ('m_price', models.FloatField()),
                ('l_price', models.FloatField()),
                ('sold', models.PositiveIntegerField()),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
