# Generated by Django 4.1.7 on 2023-03-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_id', models.IntegerField()),
                ('unit', models.PositiveIntegerField()),
                ('size', models.CharField(max_length=8)),
                ('price', models.IntegerField()),
                ('order_by', models.CharField(max_length=64)),
                ('order_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
