# Generated by Django 4.1.7 on 2023-03-13 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0004_carts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='l_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='m_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='s_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='sold',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
