# Generated by Django 4.1.7 on 2023-03-14 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0005_alter_menu_description_alter_menu_l_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='l_price',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='m_price',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='rating',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='s_price',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='sold',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
